steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMG}', '.']
images:
  - '${_IMG}'
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _IMG: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/tour-images/tour:latest